version: '3.7'

services:
  db:
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - drinkme:/var/lib/postgresql/data/

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    restart: unless-stopped

volumes:
  drinkme:
