version: '3.7'

services:
  db:
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - drinkme:/var/lib/postgresql/data/

volumes:
  drinkme:
